### ISSUE TITLE
API: Schedule/Calender Integration

### ISSUE THREAD

**Issue by qqwa** [ExLeonem/MOCO_APP#2]
+ get schedule: TODO
+ set schedule: TODO

---

What is part of a schedule?

Server side only Date/Time with Mode for led.

---

Should the server know if a schedule repeats itself or does the app create individual entries on the server for it, updates the server every x hours.

---

Calender Integration should probably be handled completely by the app, as the server could be used by multiple users. The app makes sure to sync calender entries as schedules to the server. We may need a way to keep track from what a schedule was created. So a user can remove a calender integration and all schedules added by it will get removed to.
Idea every schedule gets a unique id or UUID by the server which gets returned with schedule creation and the app stores it with a reference how it was crated. So a calender integration has a list of ids, which can then be used to remove the calender integration and all schedules created by it.

**Comment by ExLeonem** [comment]
We could use the MAC-Address to track the device which created the entry. Doing it that way we could generate entries for calendar integration locally, compare them and then send them to the server. The server then only send and approval if the entry was accepted.

I clearly suggest that the server itself knows the repetitions of a schedule, else we end up with a need for synchronisation which could end up in an functionality gap.

As for the parts of the schedule we could use the following attributes.

- UUID (see package: [here](https://github.com/rebeccahughes/react-native-device-info#getdeviceid)
- Time
- Date
- Calendar (type of calendar integration and id of included date)
- Repetitions (weekdays, weekly, monthly, yearly,  no specific dates)
- Mode (sun/individual, maybe pass object with easing easing?)
- Color (in rgb)

following json-structure could be imagined:

`
 {
   uuid: "E5:12:D8:E5:69:97",
   integration: {
      id: 1,
      type: "none"
   },
   activetOn:  "2018/11/28 18:00",
   repeat: [ "monday", "thursday", "friday"]
   mode: "sun",
   color: "#FFFF00"
}
`
